/// Sentinel crate_id for unresolved identifiers (ADR 2 D10 open-world).
pub(crate) const UNRESOLVED_CRATE_ID: u32 = u32::MAX;

/// Well-known Rust primitives that map to `Type::Primitive`.
pub(super) const PRIMITIVE_TYPES: &[&str] = &[
    "bool", "char", "str", "f32", "f64", "i8", "i16", "i32", "i64", "i128", "isize", "u8", "u16",
    "u32", "u64", "u128", "usize", "never",
];

/// std prelude types that are auto-resolved as `Type::ResolvedPath` with an
/// `std` external crate reference (ADR 2 D11).
pub(crate) const STD_PRELUDE_TYPES: &[&str] = &[
    "Vec",
    "Option",
    "Result",
    "String",
    "Box",
    "Iterator",
    "Default",
    "Clone",
    "Copy",
    "Debug",
    "Display",
    "PartialEq",
    "Eq",
    "Hash",
    "Ord",
    "PartialOrd",
    "Send",
    "Sync",
    "Sized",
    "Unpin",
    "Drop",
    "AsRef",
    "AsMut",
    "Deref",
    "DerefMut",
    "From",
    "Into",
    "TryFrom",
    "TryInto",
    "IntoIterator",
    "DoubleEndedIterator",
    "ExactSizeIterator",
    "FnOnce",
    "FnMut",
    "Fn",
    "ToString",
    "ToOwned",
    "BorrowMut",
    "Borrow",
    "Pin",
    "PhantomData",
    "HashMap",
    "BTreeMap",
    "HashSet",
    "BTreeSet",
    "VecDeque",
    "LinkedList",
    "Arc",
    "Rc",
    "Mutex",
    "RwLock",
];
