//! Canonical-block suspicion detection in rendered Markdown files.
//!
//! Scans `plan.md` for fenced code blocks longer than 10 lines that lack an
//! "example" marker. Such blocks may be canonical blocks leaking into the
//! rendered view. Findings are warning-only and never fail CI.
//!
//! Per ADR 2026-04-19-1242 §Q3.

use std::path::Path;

use domain::verify::VerifyFinding;

/// Scan a Markdown file for fenced code blocks longer than 10 lines.
///
/// Emits a `VerifyFinding::warning` for each suspicious block (file + line number).
/// Blocks with an ADR-style "example" marker are excluded. The marker is recognized in:
/// 1. The line immediately preceding the opening fence.
/// 2. The info string on the opening fence line itself (e.g., ` ```example `).
///
/// Inner-line scanning is intentionally excluded to avoid false negatives from block
/// content that happens to contain example-marker text.
///
/// Each line is normalized by `fence_line_normalize` before fence detection: blockquote
/// `> ` markers are stripped recursively and all leading whitespace is removed. The same
/// normalization is applied consistently to every line — opening fence, inner body lines,
/// and closing fence — so that fenced blocks at any container depth are detected and
/// their boundaries are correctly matched.
///
/// Known accepted deviation: `plan.md` is a flat rendered view generated by `sotp`.
/// It does not use CommonMark indented code blocks (4-space indent) or embed literal
/// fence delimiters (`` ``` ``, `~~~`) as body content inside fenced blocks. Treating
/// these edge cases as fence delimiters would result in spurious warnings, but this is
/// acceptable because: (a) the patterns never appear in practice in the target file,
/// and (b) the canonical-block warning is suppression-only and never fails CI — false
/// positives can always be suppressed with an example marker.
///
/// Recognized preceding-line markers (case-insensitive, matched on normalized text):
/// - `<!-- illustrative, non-canonical -->` — canonical ADR Q3 marker (ADR 2026-04-19-1242 §Q3)
/// - `<!-- example -->` or `<!-- example:` — HTML comment markers
/// - `// example` — C-style line comment (word-boundary match)
///
/// Fence-open inline marker (case-insensitive info string, word-boundary match):
/// - ` ```example ` / ` ~~~example ` — "example" as a whole word in the info string
pub(crate) fn scan_canonical_block_suspicion(
    doc_path: &Path,
    doc_label: &str,
    findings: &mut Vec<VerifyFinding>,
) {
    let content = match std::fs::read_to_string(doc_path) {
        Ok(c) => c,
        Err(e) => {
            // Symlink guard already confirmed the file is present; a read failure here
            // is unexpected and should fail at error level, consistent with other I/O
            // failures in this verifier.
            findings.push(VerifyFinding::error(format!(
                "canonical-block scan: cannot read {doc_label}: {e}"
            )));
            return;
        }
    };

    let lines: Vec<&str> = content.lines().collect();
    let mut i = 0;
    while i < lines.len() {
        // Safe: loop invariant guarantees i < lines.len()
        let raw_line = lines.get(i).copied().unwrap_or("");

        // Opening-fence detection: strip blockquote prefixes and ALL leading whitespace
        // so that fenced blocks at any container depth are visible.
        let line = fence_line_normalize(raw_line);

        // Detect opening fence: line starting with ``` or ~~~ (CommonMark fenced code block).
        // Returns both the fence character and the opening fence length (>= 3) so that
        // the closing fence can be validated per CommonMark (must be >= opening length).
        if let Some((fence_kind, open_len)) = detect_fence_open(line.as_str()) {
            let fence_start = i;
            let preceding_line = if i > 0 { lines.get(i - 1).copied() } else { None };

            // Example markers are recognized in two places only, to avoid false negatives
            // from block content that happens to contain marker text:
            //   1. The line immediately preceding the opening fence.
            //   2. The info string on the opening fence line itself (e.g., "```example").
            // Inner-line scanning is intentionally excluded.
            let fence_open_has_example = fence_info_has_example(line.as_str());

            // Closing-fence detection: apply the same `fence_line_normalize` as opening.
            // This is consistent: blockquote-level fences find their closers correctly,
            // and the scanner applies the same transformation at every container depth.
            // `plan.md` is a generated flat view that does not contain `` ``` `` as
            // literal text inside fenced code block bodies.
            let mut j = i + 1;
            while j < lines.len() {
                // Safe: loop invariant guarantees j < lines.len()
                let inner_raw = lines.get(j).copied().unwrap_or("");
                let inner = fence_line_normalize(inner_raw);
                if is_fence_close(inner.as_str(), fence_kind, open_len) {
                    break;
                }
                j += 1;
            }

            // Count lines inside the fence (excluding opening and closing fence lines).
            let block_line_count = j.saturating_sub(fence_start + 1);

            if block_line_count > 10 {
                // Normalize the preceding line (strip container prefixes) before checking
                // for an example marker so that markers inside blockquotes are recognized.
                let preceding_has_example = preceding_line
                    .is_some_and(|l| is_example_marker(fence_line_normalize(l).as_str()));

                if !preceding_has_example && !fence_open_has_example {
                    findings.push(VerifyFinding::warning(format!(
                        "canonical-block suspicion: {doc_label} line {} has a fenced code block \
                         with {block_line_count} lines — may be a canonical block leaking into a \
                         rendered view (add an example marker to suppress)",
                        fence_start + 1
                    )));
                }
            }

            // Advance past the closing fence (or end of file if unclosed).
            i = if j < lines.len() { j + 1 } else { j };
        } else {
            i += 1;
        }
    }
}

/// Normalize a raw Markdown line for fence detection.
///
/// 1. Strips blockquote `> ` markers (0-3 leading spaces + `>` + optional space) recursively
///    so that fenced blocks inside blockquotes are detected.
/// 2. Strips all remaining leading and trailing whitespace.
///
/// Step 2 means that indented lines (e.g., 4-space indented) are also treated as fence
/// candidates after blockquote stripping. This is intentional for `plan.md`, which is
/// a flat rendered view generated by `sotp` and does not use CommonMark indented code
/// blocks in practice. The same normalization is applied to every line — opening fence,
/// inner body lines, and closing fence — so the scanner is self-consistent across all
/// container depths.
fn fence_line_normalize(line: &str) -> String {
    strip_container_prefix(line).trim().to_owned()
}

/// Strip CommonMark blockquote container prefixes from a line.
///
/// A blockquote prefix consists of 0-3 leading spaces followed by `>` and an optional
/// single space. This function strips as many such prefixes as are present (recursive
/// nesting), returning the innermost content.
///
/// Example:
/// - `"   > > ```rust"` → `"```rust"`  (two levels of blockquote stripped)
/// - `"> line"` → `"line"`
/// - `"normal line"` → `"normal line"`  (unchanged)
fn strip_container_prefix(line: &str) -> String {
    let mut s = line;
    loop {
        // Strip 0-3 optional leading spaces
        let trimmed = s.trim_start_matches(' ');
        let spaces_stripped = s.len() - trimmed.len();
        if spaces_stripped > 3 {
            // 4+ leading spaces = indented code block context; stop stripping
            break;
        }
        // Check for blockquote `>` marker
        if let Some(after_gt) = trimmed.strip_prefix('>') {
            // Optionally consume one trailing space after `>`
            s = after_gt.strip_prefix(' ').unwrap_or(after_gt);
        } else {
            break;
        }
    }
    s.to_owned()
}

/// Returns `Some((fence_char, fence_len))` if the trimmed line opens a fenced code block.
///
/// `fence_char` is `'`'` or `'~'`. `fence_len` is the number of consecutive fence
/// characters at the start of the line (>= 3). An info string (e.g. "rust") may follow
/// the fence prefix — that does not affect detection.
///
/// Per CommonMark, the closing fence must use the same character and be at least as long
/// as the opening fence. Returning the opening length allows `is_fence_close` to enforce
/// this requirement.
fn detect_fence_open(line: &str) -> Option<(char, usize)> {
    let fence_char = if line.starts_with("```") {
        '`'
    } else if line.starts_with("~~~") {
        '~'
    } else {
        return None;
    };
    let fence_len = line.chars().take_while(|&c| c == fence_char).count();
    Some((fence_char, fence_len))
}

/// Return true if a trimmed line is a valid closing fence for the given opening fence.
///
/// Per CommonMark, a closing fence:
/// - consists entirely of the same fence character as the opening fence
/// - has length >= `open_len` (the opening fence length)
///
/// This prevents a shorter fence (e.g., 3 backticks) from incorrectly closing a
/// block opened with a longer fence (e.g., 4 or more backticks).
fn is_fence_close(line: &str, fence_char: char, open_len: usize) -> bool {
    if line.len() < open_len {
        return false;
    }
    line.chars().all(|c| c == fence_char)
}

/// Return true if a line contains an ADR-style example marker.
///
/// Markers (matched case-insensitively on the trimmed normalized line):
/// - `<!-- illustrative, non-canonical -->` — canonical ADR Q3 marker (ADR 2026-04-19-1242 §Q3)
/// - `<!-- example -->` or `<!-- example:` — HTML comment markers
/// - `// example` — C-style line comment (word-boundary: not `// examples` etc.)
///
/// Deliberately excluded patterns that are too broad for plan.md:
/// - `# example` — would match Markdown section headings like `# Examples`
/// - `example:` — would match YAML content and other prose lines
fn is_example_marker(line: &str) -> bool {
    let lower = line.to_ascii_lowercase();
    if lower.contains("<!-- illustrative, non-canonical -->") {
        return true;
    }
    if lower.contains("<!-- example -->") || lower.contains("<!-- example:") {
        return true;
    }
    // `// example` with word-boundary: followed by end-of-string, space, or colon
    if let Some(rest) = lower.strip_prefix("// example") {
        if rest.is_empty() || rest.starts_with(':') || rest.starts_with(' ') {
            return true;
        }
    }
    false
}

/// Return true if the info string of a fence-open line contains "example" (case-insensitive).
///
/// The info string is the portion of the trimmed fence-open line that follows the
/// 3-character fence prefix (` ``` ` or `~~~`). For example:
/// - ` ```example ` → info string is "example" → returns true
/// - ` ```example my-block ` → info string is "example my-block" → returns true
/// - ` ```rust ` → info string is "rust" → returns false
///
/// This handles the case where the author tags the opening fence line itself with
/// "example" to mark the entire block as an intentional example.
fn fence_info_has_example(line: &str) -> bool {
    // Determine the fence character (` or ~) and strip all leading fence characters
    // to get the info string. A fence may use 3+ characters, so we strip all of them.
    let fence_char = if line.starts_with("```") {
        '`'
    } else if line.starts_with("~~~") {
        '~'
    } else {
        return false;
    };
    let info = line.trim_start_matches(fence_char);
    // Require "example" as a standalone word: preceded by start-of-string or whitespace,
    // and followed by end-of-string or whitespace. This allows ` ```example ` and
    // ` ```my example ` but rejects ` ```non-example ` and ` ```notexample `.
    let lower_info = info.to_ascii_lowercase();
    let target = "example";
    let mut search = lower_info.as_str();
    while let Some(pos) = search.find(target) {
        let before_ok = pos == 0 || search.as_bytes().get(pos - 1).is_some_and(|b| *b == b' ');
        let after_pos = pos + target.len();
        let after_ok = after_pos >= search.len()
            || search.as_bytes().get(after_pos).is_some_and(|b| *b == b' ');
        if before_ok && after_ok {
            return true;
        }
        // Advance past this occurrence; stop if at end
        search = search.get(pos + 1..).unwrap_or("");
    }
    false
}
