//! Global cross-baseline trait index for the baseline-graph renderer (T008 / O-r1).
//!
//! Implements Decision O-r1: cross-baseline global trait index construction.
//! Index key is `(CrateName, module_path_string, TraitName)`. Built once per render
//! call (not long-lived — no Arc / stale data risk). Workspace-external types are
//! silently skipped.
//!
//! (O-r1 / CN-05 / CN-10)

use std::collections::HashMap;

use rustdoc_types::{ItemEnum, Visibility};

use domain::tddd::baseline_document::BaselineDocument;

use super::node_id_generator::{module_path_from_summary, trait_node_id};

// ---------------------------------------------------------------------------
// Trait index types
// ---------------------------------------------------------------------------

/// Key for the global cross-baseline trait index (O-r1, CN-05).
///
/// - `crate_name`: the crate that *declares* the trait (resolved via
///   `ItemSummary.crate_id == 0` for own-crate traits in each baseline).
/// - `module_path`: middle path segments joined with `::` (empty for crate-root traits).
/// - `trait_name`: short trait name (last segment of `ItemSummary.path`).
///
/// Identity is name/path-based; `rustdoc::Id` values are never compared
/// across baselines (CN-05).
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub(super) struct TraitKey {
    pub(super) crate_name: String,
    pub(super) module_path: String,
    pub(super) trait_name: String,
}

/// Global cross-baseline trait index (O-r1).
///
/// Maps `(crate_name, module_path, trait_name)` → `trait_subgraph_id` (the
/// mermaid subgraph id generated by [`trait_node_id`]). Built once per render
/// call inside the rendering function — not stored in adapter state (CN-04).
pub(super) type TraitIndex = HashMap<TraitKey, String>;

// ---------------------------------------------------------------------------
// Trait index construction
// ---------------------------------------------------------------------------

/// Build the global trait index from all baselines (O-r1).
///
/// Scans every baseline once: for each `ItemEnum::Trait` item in `krate.index`
/// whose `crate_id == 0` (own-crate) and that is present in `krate.paths`,
/// derives `(crate_name, module_path, trait_name)` and maps it to the mermaid
/// subgraph id generated by [`trait_node_id`].
///
/// Workspace-external traits (`crate_id != 0`) are silently skipped (CN-10).
///
/// # Panics
///
/// This function never panics; all indexing uses `.get()` / iterators.
pub(super) fn build_trait_index(baselines: &[BaselineDocument], layer: &str) -> TraitIndex {
    let mut index = TraitIndex::new();

    for doc in baselines {
        if doc.layer.as_ref() != layer {
            continue;
        }
        let krate = &doc.krate;
        let own_crate_name = doc.crate_name.as_str();

        for (id, item) in &krate.index {
            // Own-crate items only (crate_id == 0).
            if item.crate_id != 0 {
                continue;
            }
            // Visibility filter (CC-1): only Public traits are indexed.
            // `extract_nodes` only renders Public top-level entries, so indexing a
            // non-public trait would create a phantom subgraph target when an edge is
            // emitted toward it.
            if !matches!(item.visibility, Visibility::Public) {
                continue;
            }
            if !matches!(item.inner, ItemEnum::Trait(_)) {
                continue;
            }
            // Must be in krate.paths to have a canonical module path.
            let summary = match krate.paths.get(id) {
                Some(s) => s,
                None => continue,
            };

            // Derive module_path (middle segments, "::" joined) for the key.
            // summary.path = [crate_name, module_seg1, ..., trait_name]
            let module_path = module_path_str_from_summary(&summary.path);

            // trait_name = last segment.
            let trait_name = match summary.path.last() {
                Some(n) => n.clone(),
                None => continue,
            };

            // trait_subgraph_id via D-decision node_id generator.
            // module_path for node_id uses `_`-joined form (for node_id generator input).
            let module_path_for_id = module_path_from_summary(&summary.path);
            let trait_subgraph_id =
                trait_node_id(layer, own_crate_name, &module_path_for_id, &trait_name);

            let key = TraitKey { crate_name: own_crate_name.to_string(), module_path, trait_name };
            index.insert(key, trait_subgraph_id);
        }
    }

    index
}

/// Resolve a `rustdoc_types::Path` to its `(CrateName, module_path, TraitName)` key
/// for trait index lookup (O-r1).
///
/// Uses `Path.id` to look up `ItemSummary` in `krate.paths` (not `Path.path` — that
/// can be a re-export / alias form). Then resolves `crate_id` via
/// `krate.external_crates`. Returns `None` if any lookup step fails (silent skip,
/// CN-10).
///
/// `crate_id == 0` resolves to `impl_crate_name` (the crate that *contains* the
/// Impl item). Non-zero `crate_id` values are resolved through `krate.external_crates`
/// to get the declaring crate's name (O-r1 ADR §309). If the `crate_id` is not found
/// in `external_crates` (e.g. the trait is from an unknown dependency), `None` is
/// returned (silent skip, CN-10). The caller's trait index lookup will then decide
/// whether the resulting `TraitKey` maps to an indexed workspace trait.
///
/// `impl_crate_name` is the crate that *contains* the Impl item (used to resolve
/// `crate_id == 0`).
pub(super) fn resolve_trait_key(
    path: &rustdoc_types::Path,
    krate: &rustdoc_types::Crate,
    impl_crate_name: &str,
) -> Option<TraitKey> {
    // Look up ItemSummary for the trait via Path.id.
    let summary = krate.paths.get(&path.id)?;

    // Resolve crate name from crate_id (O-r1 ADR §309).
    // crate_id == 0: own crate (the crate that contains this Impl item).
    // crate_id != 0: resolve via krate.external_crates to get the declaring crate name.
    //   If not found in external_crates, the trait origin is unresolvable — silent skip (CN-10).
    //   The trait_index lookup below will further filter to workspace-only traits.
    let crate_name = if summary.crate_id == 0 {
        impl_crate_name.to_string()
    } else {
        match krate.external_crates.get(&summary.crate_id) {
            Some(ext) => ext.name.clone(),
            // Not in external_crates → unresolvable origin — silent skip (CN-10).
            None => return None,
        }
    };

    // module_path = middle segments of summary.path joined with "::".
    let module_path = module_path_str_from_summary(&summary.path);

    // trait_name = last segment.
    let trait_name = summary.path.last()?.clone();

    Some(TraitKey { crate_name, module_path, trait_name })
}

/// Derive `module_path` string (`::`-joined) from an `ItemSummary.path` slice.
///
/// Used for trait index key construction (O-r1). The node_id generator uses
/// `_`-joined form; the index key uses `::`-joined to avoid ambiguity between
/// module names that contain underscores.
///
/// Returns an empty string for crate-root items (path length ≤ 2).
pub(super) fn module_path_str_from_summary(path: &[String]) -> String {
    let total = path.len();
    if total <= 2 {
        return String::new();
    }
    let middle_count = total - 2;
    path.iter().skip(1).take(middle_count).cloned().collect::<Vec<_>>().join("::")
}
